name: Run ETL job on the EC2 instance

on:
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
  EC2_PUBLIC_DNS: ${{ secrets.EC2_PUBLIC_DNS }}

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Prepare SSH key
      run: |
        echo "$EC2_PRIVATE_KEY" > id_rsa
        chmod 600 id_rsa

    - name: Copy ETL job to EC2 instance
      run: |
        scp -v -o StrictHostKeyChecking=no -i id_rsa etl-job.py ubuntu@${EC2_PUBLIC_DNS}:~/etl_job.py

    - name: Install dependencies on EC2 instance
      run: |
        ssh -v -o StrictHostKeyChecking=no -i id_rsa ubuntu@${EC2_PUBLIC_DNS} '
          sudo apt-get update && sudo apt-get install -y python3-pip libpq-dev
          pip3 install boto3 psycopg2-binary
        '

    - name: Run ETL job on EC2 instance
      run: |
        ssh -v -o StrictHostKeyChecking=no -i id_rsa ubuntu@${EC2_PUBLIC_DNS} '
          export AWS_DEFAULT_REGION=${{ env.AWS_DEFAULT_REGION }}
          export AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
          export TF_VAR_PROJECT_NAME=${{ env.TF_VAR_PROJECT_NAME }}
          export RDS_ENDPOINT=${{ env.RDS_ENDPOINT }}
          export DB_USERNAME=${{ env.DB_USERNAME }}
          export DB_PASSWORD=${{ env.DB_PASSWORD }}
          python3 ~/etl_job.py
        '

    - name: Cleanup SSH key
      run: |
        rm id_rsa
