name: ETL | Run ETL job on the EC2 instance

on:
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
  EC2_PUBLIC_DNS: ${{ secrets.EC2_PUBLIC_DNS }}

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Transfer ETL script to EC2 instance
      run: |
        echo "$EC2_PRIVATE_KEY" | ssh -o StrictHostKeyChecking=no -i /dev/stdin ubuntu@${EC2_PUBLIC_DNS} "cat > /tmp/id_rsa && chmod 600 /tmp/id_rsa"
        scp -i /tmp/id_rsa -o StrictHostKeyChecking=no scripts/etl-job.py ubuntu@${EC2_PUBLIC_DNS}:~/etl_job.py

    - name: Install dependencies on EC2 instance
      run: |
        echo "$EC2_PRIVATE_KEY" | ssh -o StrictHostKeyChecking=no -i /dev/stdin ubuntu@${EC2_PUBLIC_DNS} '
          sudo apt-get update && sudo apt-get install -y python3-pip libpq-dev
          pip3 install boto3 psycopg2-binary
        '

    - name: Execute ETL job on EC2 instance
      run: |
        echo "$EC2_PRIVATE_KEY" | ssh -o StrictHostKeyChecking=no -i /dev/stdin ubuntu@${EC2_PUBLIC_DNS} '
          export AWS_DEFAULT_REGION=${{ env.AWS_DEFAULT_REGION }}
          export AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
          export TF_VAR_PROJECT_NAME=${{ env.TF_VAR_PROJECT_NAME }}
          export RDS_ENDPOINT=${{ env.RDS_ENDPOINT }}
          export DB_USERNAME=${{ env.DB_USERNAME }}
          export DB_PASSWORD=${{ env.DB_PASSWORD }}
          python3 ~/etl_job.py
        '

    - name: Clean up temporary SSH key on EC2
      run: |
        echo "$EC2_PRIVATE_KEY" | ssh -o StrictHostKeyChecking=no -i /dev/stdin ubuntu@${EC2_PUBLIC_DNS} 'rm /tmp/id_rsa'
