name: AWS | Teardown everything on AWS

on:
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  TF_VAR_EC2_PUBLIC_KEY: ${{ vars.EC2_PUBLIC_KEY }}
  TF_VAR_DB_USERNAME: ${{ vars.DB_USERNAME }}
  TF_VAR_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  job:
    name: terraform destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get account ID and define bucket name
        run: |
          account_id=$(aws sts get-caller-identity --query Account --output text)
          echo "account_id=$account_id" >> "$GITHUB_ENV"
          echo "bucket_name=tf-$account_id-${{ vars.PROJECT_NAME }}" >> "$GITHUB_ENV"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform/aws
          terraform init -backend-config="bucket=$bucket_name"

      - name: Terraform Refresh
        run: |
          cd terraform/aws
          terraform refresh

      - name: Terraform Destroy
        run: |
          cd terraform/aws
          terraform destroy -auto-approve=true || true
